### ISSUE TITLE
Drop chance for armor doesnt play well with armor stands

### ISSUE THREAD

**Issue by EvanSkiStudios** [EvanSkiStudios/Raccoon-Mischief#28]
```
[20:04:01 ERROR]: Could not pass event EntityDeathEvent to RaccoonMischief v2.3.0
java.lang.IllegalArgumentException: Cannot set drop chance for non-Mob entity
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftEntityEquipment.setDropChance(CraftEntityEquipment.java:260) ~[paper-1.20.1.jar:git-Paper-19]
	at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftEntityEquipment.setHelmetDropChance(CraftEntityEquipment.java:215) ~[paper-1.20.1.jar:git-Paper-19]
	at me.evanskistudios.rm.Listeners.ListenerEntityDeath.onMobDeath(ListenerEntityDeath.java:28) ~[RaccoonMischief-2.3.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor8.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-19]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-19]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-19]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:897) ~[paper-1.20.1.jar:git-Paper-19]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:889) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.world.entity.decoration.ArmorStand.kill(ArmorStand.java:768) ~[?:?]
	at net.minecraft.world.entity.decoration.ArmorStand.hurt(ArmorStand.java:495) ~[?:?]
	at net.minecraft.world.level.Explosion.explode(Explosion.java:262) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.world.level.Level.explode(Level.java:990) ~[?:?]
	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1885) ~[?:?]
	at net.minecraft.world.level.Level.explode(Level.java:956) ~[?:?]
	at net.minecraft.world.entity.monster.Creeper.explodeCreeper(Creeper.java:274) ~[?:?]
	at net.minecraft.world.entity.monster.Creeper.tick(Creeper.java:162) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1352) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:919) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:872) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1543) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-19]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
	```

**Comment by EvanSkiStudios** [comment]
fixed by making sure entity is always of the monster class

```java
       if (!(Entity instanceof Monster)){
            return;
        }
```
